name: client
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  http: ^0.12.2
  web_socket_channel: ^1.2.0
  logging: ^0.11.4

dev_dependencies:
  pedantic: ^1.9.0
